version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8100:8100"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - quicksters-net

  api:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./backend/src:/app
    depends_on:
      - db
    networks:
      - quicksters-net

    command: python app.py

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=quicksters_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - quicksters-net
    command: --default-authentication-plugin=mysql_native_password
      
volumes:
  mysql_data:

networks:
  quicksters-net:
    driver: bridge